// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rytpbfpgkswojbsyankv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dHBiZnBna3N3b2pic3lhbmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODkxODUsImV4cCI6MjA2MDQ2NTE4NX0.N-BjgX2y7oD92mxADLmY9Hk93t10t92it1L0GvyHAk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);