# .github/workflows/docker-publish.yml

name: Build and Push Frontend Docker Image

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a standard GitHub-hosted runner (which is amd64)

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up QEMU for multi-platform builds (needed if runner differs, good practice)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and push the Docker image
      # This step builds for linux/amd64 and pushes to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v6 # Use a recent version
        with:
          context: . # Build context is the root of the repository
          file: ./Dockerfile # Path to your frontend Dockerfile
          platforms: linux/amd64 # Specify the target platform
          push: true # Actually push the image
          tags: chekuhakim/mail-task-frontend:latest # The tag for your Docker Hub repo

